config/routes.rb
Rails.application.routes.draw do
  
  resources :member_events do
    member do
      get :delete
      patch :approve
      patch :unapprove
    end
  end
  
  root "main#index"

  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end


  get 'main/index'
  resources :faqs

  # get 'members/index'
  # get 'members/new'
  # get 'members/edit'
  
  # routs for the member status pages
  get 'members/update_status', to: 'members#update_status', as: 'edit_status'
  post 'members/update_status', to: 'members#update_status', as: 'update_status'

  resources :members do
    member do
      get :delete
    end
  end

  resources :committees
  resources :excuses do 
    member do
      get :delete
    end
  end

  resources :committees do
    member do
      get :delete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :excuses do
    member do
      patch :approve
      patch :unapprove
    end
  end

  resources :events do
    member do 
      get :delete
    end
  end
  
  resources :events
end

app/models/member_event.rb
class MemberEvent < ApplicationRecord
  belongs_to :member
  belongs_to :event

  # checks if phrase is equal to is event phrase, wont check if there is no event 
  validate :phrase_matches_event_phrase
  has_one_attached :file

  before_validation :dependencies

  # when saving, update values given approval status
  before_save do
    self.approved_status = false if approved_status.nil?
    if (approved_status == true) then
      self.approve_date = DateTime.now if approve_date.blank?
    else
      self.approve_date = nil
    end
  end

  # checks to see if phrase matches the meetings phrase
  def phrase_matches_event_phrase
    unless self.event.nil?
      if self.event.event_type == 'Meeting'
        errors.add(:phrase, 'Entered wrong password try again') unless self.phrase == event.phrase
      end
    end
  end


  # function that checks if the event exists. 
  def event_exists?
    event.present?
  end

  private 
  # checks to see you have approve by before submitting
  def dependencies 
    if (self.event&.event_type == 'Service' || self.event&.event_type == 'Personal/Non-Event') && self.approve_by == ''
      errors.add(:approve_by, "cannot be empty")
      return false
    end
  end

end

app/controllers/member_events_controller.rb
class MemberEventsController < ApplicationController
  before_action :set_member_event, only: %i[ show edit update destroy ]

  # sets the member before each action 
  before_action :set_member 

  # admin validation for certain pages (will be determined on later date)
  before_action :authorize_admin, only: %i[update destroy delete approve unapprove]
  before_action :member_admin_deletion_protection
  before_action :authenticate_user


  def approve
    @member_event = MemberEvent.find(params[:id])
    @member_event.update(approved_status: true)

    if @member_event.event.point_type == "Civic Engagement"
      @member_event.member.civicPoints += 1
    elsif @member_event.event.point_type == "Marketing"
      @member_event.member.marketingPoints += 1
    elsif @member_event.event.point_type == "Social"
      @member_event.member.socialPoints += 1
    elsif @member_event.event.point_type == "Outreach"
      @member_event.member.outreachPoints += 1
    end
    @member_event.member.save
    
    redirect_to @member_event
  end

  def unapprove
    @member_event = MemberEvent.find(params[:id])
    @member_event.update(approved_status: false)

    if @member_event.event.point_type == "Civic Engagement"
      @member_event.member.civicPoints -= 1
    elsif @member_event.event.point_type == "Marketing"
      @member_event.member.marketingPoints -=1
    elsif @member_event.event.point_type == "Social"
      @member_event.member.socialPoints -= 1
    elsif @member_event.event.point_type == "Outreach"
      @member_event.member.outreachPoints -=1
    end

    @member_event.member.save    
    redirect_to @member_event
  end

  # GET /member_events or /member_events.json
  def index
    @member_events = MemberEvent.all
    @service_events = MemberEvent.all

    # filter service if event type present in submission
    if params[:service_status].present?
      if params[:service_status] == 'All'
        @service_events = MemberEvent.all
      elsif params[:service_status] == 'Approved'
        @service_events = MemberEvent.where('approved_status = true').all
      elsif params[:service_status] == 'Pending'
        @service_events = MemberEvent.where('approved_status = false').all
      end
      # if service_status not present do regular filtering
      else 
        @service_events = MemberEvent.all
      end
    end

  # GET /member_events/1 or /member_events/1.json
  def show
    
    # ensures that members does not access member_event that is not theirs
    @member_event = MemberEvent.find(params[:id])
    if @user.id != @member_event.member_id && @user.position == 'Member'
      if @member_event.event.event_type == 'Service'
        redirect_to root_path, notice: 'You do not have access to that service submission'
      elsif @member_event.event.event_type == 'Meeting'
        redirect_to root_path, notice: 'You do not have access to that meeting submission'
      else
        redirect_to root_path, notice: 'You do not have access to that Personal/Non-Event'
      end
    end
  end

  # GET /member_events/new
  def new
    @member_event = MemberEvent.new

    # creates version of page for service or meeting that defaults to version 1
    @version = params[:version] || '1'

  end

  # for deletion page
  def delete
    @member_event = MemberEvent.find(params[:id])
  end

  # GET /member_events/1/edit
  def edit

    # ensures that members does not access member_event that is not theirs
    @member_event = MemberEvent.find(params[:id])
    if @user.id != @member_event.member_id && @user.position == 'Member'
      if @member_event.event.event_type == 'Service'
        redirect_to root_path, notice: 'You do not have access to that service submission'
      elsif @member_event.event.event_type == 'Meeting'
        redirect_to rooth_path, notice: 'You do not have access to that meeting submission'
      else
        redirect_to root_path, notice: 'You do not have access to that Personal/Non-Event'
      end
    end

    @version = params[:version] || '1'
  end

  # POST /member_events or /member_events.json
  def create # rubocop:todo Metrics/AbcSize, Style/InlineComment
    custom_value = ""
    officers = params[:member_event][:officer_ids] || []

    # loops through to populate custom_value which will be used to make approve by 
    officers.each_with_index do |officer, index|
      if index == officers.length - 1
        custom_value += officer.to_s
      else 
        custom_value += officer.to_s + ", "
      end
    end

    @member_event = MemberEvent.new(event_id: params[:member_event][:event_id],
                                    member_id: params[:member_event][:member_id],
                                    approved_status: params[:member_event][:approved_status],
                                    approve_date: params[:member_event][:approve_date],
                                    approve_by: params[:member_event][:approve_by],
                                    phrase: params[:member_event][:phrase],
                                    file: params[:member_event][:file],
                                    description: params[:member_event][:description])


    # enters name of member so user doesnt have to do it in form
    @member_event.member_id = @user.id
    @member_event.approve_by = custom_value

    respond_to do |format|
      if @member_event.save
        # if member_event is for a meeting then give a meeting message, if not give a member event message 
        if @member_event.event.event_type == 'Meeting'
          format.html { redirect_to member_event_url(@member_event), notice: 'You successfully signed into meeting' }
        elsif @member_event.event.event_type == 'Personal/Non-Event'
          format.html { redirect_to member_event_url(@member_event), notice: 'Personal/Non-Event was successfully submitted.' }
        else
          format.html { redirect_to member_event_url(@member_event), notice: 'Service was successfully submitted.' }
        end
        format.json { render :show, status: :created, location: @member_event }
      else
        session[:version] = params[:version]
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_events/1 or /member_events/1.json
  def update
    respond_to do |format|
      approve_by_placeholder = @member_event.approve_by
      # loops through to populate custom_value which will be used to make approve by 
      custom_value = ""
      officers = params[:member_event][:officer_ids] || []
      officers.each_with_index do |officer, index|
        if index == officers.length - 1
          custom_value += officer.to_s
        else 
          custom_value += officer.to_s + ", "
        end
      end

      previous_approval = @member_event.approved_status

      # get rid of officer_ids before updating 
      params[:member_event].delete(:officer_ids)

      if @member_event.update(member_event_params)
        
        # keeps old approve_by if nothin was changed 
        if custom_value == ""
          @member_event.approve_by = approve_by_placeholder
          @member_event.save
        else
          @member_event.approve_by = custom_value
          @member_event.save
        end

        # if member_event is for a meeting then give a meeting message, if not give a member event message 
        if @member_event.event.event_type == 'Meeting'
          format.html {redirect_to member_event_url(@member_event), notice: 'Member Sign in was successfully updated.'}
        elsif @member_event.event.event_type == 'Personal/Non-Event'
          format.html { redirect_to member_event_url(@member_event), notice: 'Personal/Non-Event was successfully updated.' }
        else
          format.html { redirect_to member_event_url(@member_event), notice: 'Service was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @member_event }

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_events/1 or /member_events/1.json
  def destroy
    type = @member_event.event.event_type
    @member_event.destroy

    if type == "Meeting"
      respond_to do |format|
          format.html { redirect_to member_events_url, notice: 'Meeting Attendance successfully destroyed.'}
          format.json { head :no_content }
      end
    elsif type == "Service" || type == "Personal/Non-Event"
      respond_to do |format|
        format.html { redirect_to member_events_url, notice: 'Service was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to member_events_url, notice: 'Member event successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_event
      @member_event = MemberEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_event_params
      params.require(:member_event).permit(:event_id, :member_id, :approved_status, :approve_date, :approve_by, :file, :version, :phrase, 
                                           :officer_ids, :description)
    end

    # sets the member before each action
    def set_member
      @user = current_admin.member
    end
    
    # protects against site crashing when deleting members
    def member_admin_deletion_protection
      if @user.nil?
        redirect_to new_member_path
      end
    end
    
    # checks to see if member is an admin 
    def authorize_admin
      @user = current_admin.member
      if @user.nil? || @user.position == 'Member' then

app/helpers/member_events_helper.rb
module MemberEventsHelper
end

app/views/member_events/_form.html.erb
<%= form_with(model: member_event) do |form| %>
  <% if member_event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member_event.errors.count, "error") %> prohibited this member_event from being saved:</h2>

      <ul>
        <% member_event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%# form for personal/Non-Event %>
    <% if @version == "3" || (member_event[:description])%>
    <div>
      <%= form.label :event_id, style: "display: block" %>
      <%# filters for member events that are services %>
      <%= form.select :event_id, Event.where(event_type: ["Personal/Non-Event"]).order(:name).map { |event| [event.name, event.id] } %>
    </div>

    <br>
    <%# makes a dropdown to where you can only see admins %>
    <% Member.where.not(position: "Member").each do |officer| %>
      <div>
        <%= form.label :officer_ids, officer.name, style: "display: block"%>
        <%= form.check_box :officer_ids, {multiple: true}, officer.name, nil %>
      </div>
    <% end %>

    <br>

    <% if member_event.file.attached? %>
      <div>
        <%= form.label :file, style: "display: block" %>
        <%= form.file_field :file, value: member_event.file %>
      </div>
    <% else %>
      <div>
        <%= form.label :file, style: "display: block" %>
        <%= form.file_field :file, value: member_event.file.url %>
      <div>
    <% end %>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <br>
    <div>
      <%= form.submit(member_event.new_record? ? "Submit Personal/Non-Event" : "Edit Personal/Non-Event") %>
    </div>
  <% end %>

  <%# form submission for services %>
  <% if @version == "1" || (member_event.errors[:phrase].any? == false && member_event.errors[:description].any? == false && member_event.errors.any? && member_event[:description].nil?) %>
  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%# filters for member events that are services %>
    <%= form.select :event_id, Event.where(event_type: ["Service"]).order(:name).map { |event| [event.name, event.id] } %>
  </div>

  <br>
  <%# makes a dropdown to where you can only see admins %>
    <% Member.where.not(position: "Member").each do |officer| %>
      <div>
        <%= form.label :officer_ids, officer.name, style: "display: block"%>
        <%= form.check_box :officer_ids, {multiple: true}, officer.name, nil %>
      </div>
    <% end %>




  <br>

  <% if member_event.file.attached? %>
    <div>
      <%= form.label :file, style: "display: block" %>
      <%= form.file_field :file, value: member_event.file %>
    </div>
  <% else %>
    <div>
      <%= form.label :file, style: "display: block" %>
      <%= form.file_field :file, value: member_event.file.url %>
    <div>
  <% end %>

  <br>
    <div>
      <%= form.submit(member_event.new_record? ? "Submit service" : "Edit service") %>
      
    </div>
   <% end %>


  <%# form submission for meetings %>
   <% if @version == "2" || member_event.errors[:phrase].any?%>
    <div>
      <%= form.label :event_id, "Meeting", style: "display: block" %>
      <%# filters for member events that are meetings  %>
      <%= form.select :event_id, Event.where(event_type: "Meeting").order(:name).map { |event| [event.name, event.id] } %>
    </div>

    <div>
      <%= form.label :phrase, style: "display: block" %>
      <%= form.text_field :phrase %>
    </div>

  <br>
    <div>
      <%= form.submit(member_event.new_record? ? "Sign into meeting" : "Edit meeting attendance") %>
    </div>
  <% end %>
<% end %>

app/views/member_events/_member_event.html.erb
<div id="<%= dom_id member_event %>">
  <% if member_event.event.event_type == "Service" || member_event.event.event_type == "Personal/Non-Event"%>
    <p>
      <strong>Event:</strong>
      <%= member_event.event.name %>
    </p>

    <p>
      <strong>Member:</strong>
      <%= member_event.member.name %>
    </p>


    <% if member_event.event.event_type == "Personal/Non-Event" %>
      <p>
        <strong>Description:</strong>
        <%= member_event.description %>
      </p>
    <% end %>

    <p>
      <strong>Approved status:</strong>
      <%= member_event.approved_status %>
    </p>

    <% if (member_event.approved_status == true) then %>

    <p>
      <strong>Approved date:</strong>
      <%= member_event.approve_date %>
    </p>
    <% end %>

    <p>
      <strong>Approved by:</strong>
      <%= member_event.approve_by %>
    </p>


    <p>
    <strong>File:</strong>
    <%= link_to member_event.file.filename, member_event.file if member_event.file.attached? %>
    </p>
  <% end %>

  <% if member_event.event.event_type == "Meeting" %>
    <p>
      <strong>Event:</strong>
      <%= member_event.event.name %>
    </p>
      <strong>Date:</strong>
      <%= member_event.event.date %>
    <p>
    <p>
      <strong>Member:</strong>
      <%= member_event.member.name %>
    </p>

  <% end %>
</div>

app/views/member_events/delete.html.erb
<%= link_to "Back to Activities", member_events_path %>

<% if @member_event.event.event_type == "Service" || @member_event.event.event_type == "Personal/Non-Event"%>
    <div class="delete">
        <h2>Destroy Service</h2>
        <%= form_for(@member_event, method: 'delete') do |f| %>
            <p>Are you sure you want to permanently delete this Submission?</p>
            <p>Event: <%= @member_event.event.name %></p>
            <p>Member: <%= @member_event.member.name %></p>
            <% if @member_event.event.event_type == "Personal/Non-Event" %>
                <p>Description: <%= @member_event.description%> <p>
            <% end %>

            <p>Approved status: <%= @member_event.approved_status %></p>
            <% if (@member_event.approved_status == true) then %>
                <p>Approved date: <%= @member_event.approve_date %></p>
            <% end %>

            <p>Approve by: <%= @member_event.approve_by %></p>
            <% if @member_event.file.attached?%>
                <p>File: <%= link_to @member_event.file.filename, @member_event.file  %></p>
            <% else %>
                <p>File: n/a</p>
            <% end %>

            <div class="form-buttons">
                <%= f.submit("Delete service") %>
            </div>
        <% end %>
    </div>
<% end %>

<% if @member_event.event.event_type == "Meeting" %>
    <div class="delete">
        <h2>Destroy Meeting</h2>
        <%= form_for(@member_event, method: 'delete') do |f| %>
            <p>Are you sure you want to permanently delete this meeting submission?</p>
            <p>Event: <%= @member_event.event.name %></p>
            <p>Member: <%= @member_event.member.name %></p>
            <div class="form-buttons">
                <%= f.submit("Delete meeting") %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/member_events/edit.html.erb
<h2>Editing Activity</h2>

<%= render "form", member_event: @member_event %>

<br>

<div>
  <%= link_to "Show this activity", @member_event %> |
  <%= link_to "Back to activities", member_events_path %>
</div>

app/views/member_events/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Activities</h2>
<%= link_to "Meeting Sign In", new_member_event_path(version: 2) %>
<br>
<%= link_to "New Service Submission", new_member_event_path(version: 1) %>
<br>
<%= link_to "New Personal/Non-Event Submission", new_member_event_path(version: 3) %>


<div id="member_events">
  <%# shows events that need to be checked off on if user is an admin %>
  <%if @user.position != "Member"%>
    <h2> My Approvals: </h2>

    <%# form submission for filtering service events by approval status %>
    <%= form_tag member_events_path, method: :get do %>
      <%= select_tag :service_status, options_for_select((["All", "Approved", "Pending"])), prompt: "Approval Status"%> 
      <%= submit_tag "Search", class: "btn btn-primary" %>
      
    <% end %>
    <table class="listing" id="Approve By list" summary="Approve By list" style="width: 100%;">
      <!-- table heads -->
      <tr class="header">
        <th class="table-head">Event</th>
        <th class="table-head">Date</th>
        <th class="table-head">Member</th>
        <th class="table-head">Approved status</th>
        <th class="table-head">Approved By</th>
        <th class="table-head">File</th>
      </tr>
      <!-- Display each member -->
      <% @service_events.each do |member_event| %>

        <% if member_event.approve_by.to_s.include?(@user.name)%>
          <tr>
            <td> <%= member_event.event.name %></td>
            <td> <%= member_event.event.date %></td>
            <td> <%= member_event.member.name %></td>
            <td> <%= member_event.approved_status %></td>
            <td> <%= member_event.approve_by %></td>
            <% if member_event.file.attached?%>
              <td> <%= link_to member_event.file.filename, member_event.file  %></td>
            <% else %>
              <td>n/a</td>
            <% end %>

            <!-- Actions for each member event -->
            <td class="actions">
              <% if member_event.approved_status == false%>
                <%= link_to("Approve", member_event_path(member_event), class: 'action show') %>
              <% elsif member_event.approved_status == true %>
                <%= link_to("Unapprove", member_event_path(member_event), class: 'action show') %>
              <% end %>

              <% if member_event.event.event_type == 'Service' %>
                <%= link_to("Edit", edit_member_event_path(member_event, version: 1), class: 'action edit') %>
              <% elsif member_event.event.event_type == 'Personal/Non-Event' %>
                <%= link_to("Edit", edit_member_event_path(member_event, version: 3), class: 'action edit') %>
              <% end %>
              <%= link_to("Delete", delete_member_event_path(member_event), class: 'action delete') %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
    <br>
  <% end %>

  <%# shows all events and Personal/Non-Events user has entered  %>
  <h2> My Services and Personal/Non-Event Submissions: </h2>
    <table class="listing" id="My Services" summary="My Services" style="width: 100%;">
      <!-- table heads -->
      <tr class="header">
        <th class="table-head">Event</th>
        <th class="table-head">Date</th>
        <th class="table-head">Approved status</th>
        <th class="table-head">Approved By</th>
        <th class="table-head">File</th>
      </tr>
      <!-- Display each member -->
      <% @member_events.each do |member_event| %>

        <% if (member_event.member_id == @user.id && member_event.event.event_type == "Service") || (member_event.member_id == @user.id && member_event.event.event_type == "Personal/Non-Event")%>
          <tr>
            <td> <%= member_event.event.name %></td>
            <td> <%= member_event.event.date %></td>
            <td> <%= member_event.approved_status %></td>
            <td> <%= member_event.approve_by %></td>
            <% if member_event.file.attached?%>
              <td> <%= link_to member_event.file.filename, member_event.file  %></td>
            <% else %>
              <td>n/a</td>
            <% end %>

            <!-- Actions for each member event -->
            <td class="actions">
              <%= link_to("Show", member_event_path(member_event), class: 'action show') %>
              <% if @user.position != "Member" %>
                <% if member_event.event.event_type == 'Service' %>
                  <%= link_to("Edit", edit_member_event_path(member_event, version: 1), class: 'action edit') %>
                <% elsif member_event.event.event_type == 'Personal/Non-Event' %>
                  <%= link_to("Edit", edit_member_event_path(member_event, version: 3), class: 'action edit') %>
                <% end %>
                <%= link_to("Delete", delete_member_event_path(member_event), class: 'action delete') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>

  <%# shows all meetings user have attended %>
  <h2> My Meetings: </h2>
    <table class="listing" id="My Meetings" summary="My Meetings" style="width: 100%;">
      <!-- table heads -->
      <tr class="header">
        <th class="table-head">Event</th>
        <th class="table-head">Date</th>
      </tr>
      <!-- Display each member -->
      <% @member_events.each do |member_event| %>

        <% if member_event.member_id == @user.id && member_event.event.event_type == "Meeting" %>
          <tr>
            <td> <%= member_event.event.name %></td>
            <td> <%= member_event.event.date %></td>

            <!-- Actions for each member event -->
            <td class="actions">
              <%= link_to("Show", member_event_path(member_event), class: 'action show') %>
                <% if @user.position != "Member" %>
                  <%= link_to("Edit", edit_member_event_path(member_event), class: 'action edit') %>
                  <%= link_to("Delete", delete_member_event_path(member_event), class: 'action delete') %>
                <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>

    <%if @user.position != "Member"%>
    <h2> Approvals: </h2>
    <table class="listing" id="Approve By list" summary="Approve By list" style="width: 100%;">
      <!-- table heads -->
      <tr class="header">
        <th class="table-head">Event</th>
        <th class="table-head">Date</th>
        <th class="table-head">Member</th>
        <th class="table-head">Approved status</th>
        <th class="table-head">Approved By</th>
        <th class="table-head">File</th>
      </tr>
      <!-- Display each member -->
      <% @service_events.each do |member_event| %>
          <tr>
            <td> <%= member_event.event.name %></td>
            <td> <%= member_event.event.date %></td>
            <td> <%= member_event.member.name %></td>
            <td> <%= member_event.approved_status %></td>
            <td> <%= member_event.approve_by %></td>
            <% if member_event.file.attached?%>
              <td> <%= link_to member_event.file.filename, member_event.file  %></td>
            <% else %>
              <td>n/a</td>
            <% end %>

          </tr>
        <% end %>
      <% end %>
    </table>
    <br>
</div>

app/views/member_events/new.html.erb
<%# title for services  %>
<% if @version == "1" %>
  <h2>New Service Submission</h2>
<% end %>

<% if @version == "3" %>
  <h2>New Personal/Non-Event Submission</h2>
<% end %>

<%# title for meetings %>
<% if @version == "2" %>
  <h2>Meeting Sign In</h2>
<% end %>

<%= render "form", member_event: @member_event %>

<br>

<div>
  <%= link_to "Back to Activities", member_events_path %>
</div>

app/views/member_events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member_event %>

<div>

  <%# go to version 1 if type is service %>
  
  <%# give admins the ability to approve/disapprove services %>
  <% if @user.position != "Member" && (@member_event.event.event_type == "Service" || @member_event.event.event_type == "Personal/Non-Event") %>
    <% if !@member_event.approved_status %>
      <%= form_tag approve_member_event_path(@member_event), method: :patch do %>
        <%= submit_tag "Approve" %>
      <% end %>
    <% end %>

    <% if @member_event.approved_status %>
      <%= form_tag unapprove_member_event_path(@member_event), method: :patch do %>
        <%= submit_tag "Undo Approval" %>
      <% end %>
    <% end %>
  <% end %>

  <% if @member_event.event.event_type == "Service" %>
    <%= link_to "Edit this service", edit_member_event_path(@member_event, version: 1 ) %> |
  <% end %>

  <% if @member_event.event.event_type == "Personal/Non-Event" %>
    <%= link_to "Edit this Personal/Non-Event", edit_member_event_path(@member_event, version: 3) %> |
  <% end %>

 <%# go to version 2 if type is meeting %>
  <% if @member_event.event.event_type == "Meeting" %>
      <% if @user.position != "Member"%>
        <%= link_to "Edit this meeting submission", edit_member_event_path(@member_event, version: 2) %> |
      <% end %>
  <% end %>

  <%= link_to "Back to activities", member_events_path %> |

  <% unless @user.position == "Member" %>
    <% if @member_event.event.event_type == "Meeting"%>
      <%= link_to "Delete this meeting submission", delete_member_event_path(@member_event), class: "action delete" %>
    <% elsif @member_event.event.event_type == "Service" || @member_event.event.event_type == "Personal/Non-Event" %>
      <%= link_to "Delete this service", delete_member_event_path(@member_event), class: "action delete" %>
    <% end %>
  <% end %>
</div>