config/routes.rb
Rails.application.routes.draw do
  
  resources :member_events do
    member do
      get :delete
      patch :approve
      patch :unapprove
    end
  end
  
  root "main#index"

  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end


  get 'main/index'
  resources :faqs

  # get 'members/index'
  # get 'members/new'
  # get 'members/edit'
  
  # routs for the member status pages
  get 'members/update_status', to: 'members#update_status', as: 'edit_status'
  post 'members/update_status', to: 'members#update_status', as: 'update_status'

  resources :members do
    member do
      get :delete
    end
  end

  resources :committees
  resources :excuses do 
    member do
      get :delete
    end
  end

  resources :committees do
    member do
      get :delete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :excuses do
    member do
      patch :approve
      patch :unapprove
    end
  end

  resources :events do
    member do 
      get :delete
    end
  end
  
  resources :events
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :events, through: :member_events
  has_many :member_events, dependent: :destroy

  validates :date, :name, :event_type, presence: true
  validate :meeting_phrase
  validate :service_point_type
  validate :non_event_point_type
  validate :formatting

  before_save do
    self.name = name.strip unless name.nil?
  end

  private
  # if there is a meeting needs to be phrase 
  def meeting_phrase
    if (event_type == 'Meeting') && phrase.blank?
      errors.add(:phrase, "can't be blank when there is a meeting")
    end
  end

  def service_point_type
    if (event_type == 'Service') && point_type.blank?
      errors.add(:point_type, "point type can't be blank when there is a service")
    end
  end
  
  # if there is a non-event needs to have point type
  def non_event_point_type
    if (event_type == 'Personal/Non-Event') && point_type.blank?
      errors.add(:point_type, "point type can't be blank when there is a non-event")
    end
  end

  # ensure that correct input formats are used
  def formatting
    # name only has letters, numbers, apostraphes, and space characters
    errors.add(:name, 'name cannot have non-word characters') if !name.nil? && !name.match?(/^[\w'\s]*$/)
  end
end

app/controllers/events_controller.rb
require 'google/apis/calendar_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'
class EventsController < ApplicationController
  before_action :set_event, :service_or_meeting, only: %i[ show edit update destroy ]
  before_action :set_member
  before_action :member_admin_deletion_protection
  before_action :authenticate_user
  before_action :authenticate_admin, only: %i[ edit update destroy new delete create]


  # GET /events or /events.json
  def index
    @events = Event.all

    # condition that checks if the month and year are presents and queries the database to return all events satisfying the months and dates
    if params[:date].present?
      if params[:date][:year].present? && params[:date][:month].present?
        start_date = Date.new(params[:date][:year].to_i, params[:date][:month].to_i, 1)
        end_date = start_date.end_of_month
        formatted_date_beg = start_date.strftime('%Y-%m-%d')
        formatted_date_end = end_date.strftime('%Y-%m-%d')

        # filter events if event type is present in submission
        if params[:event_type].present?
          if params[:event_type] == 'Any'
            @events = Event.where('date >= ? AND date <= ?', formatted_date_beg, formatted_date_end).all
          else
            event_type = params[:event_type]
            @events = Event.where('date >= ? AND date <= ? AND event_type = ?', formatted_date_beg, formatted_date_end, event_type).all
          end
        # if event type not present do regular filtering
        else 
          @events = Event.where('date >= ? AND date <= ?', formatted_date_beg, formatted_date_end).all
        end
        
      # need to have year if month is selected
      elsif (!params[:date][:year].present? && params[:date][:month].present?) || (!params[:date][:year].present? && params[:date][:month].present?)
        redirect_to events_path, notice: 'Month needs a year for submission'
      
      # if year but no months
      elsif (params[:date][:year].present?)
        start_date = Date.new(params[:date][:year].to_i, 1, 1)
        end_date = start_date.end_of_year
        formatted_date_beg = start_date.strftime('%Y-%m-%d')
        formatted_date_end = end_date.strftime('%Y-%m-%d')
        if params[:event_type].present?
          if params[:event_type] == 'Any'
            @events = Event.where('date >= ? AND date <= ?', formatted_date_beg, formatted_date_end).all
          else
            event_type = params[:event_type]
            @events = Event.where('date >= ? AND date <= ? AND event_type = ?', formatted_date_beg, formatted_date_end, event_type).all
          end
        else 
          @events = Event.where('date >= ? AND date <= ?', formatted_date_beg, formatted_date_end).all
        end

      # if only event_type is entered
      elsif params[:event_type].present?
        event_type = params[:event_type]
        if event_type == 'Any'
          @events = Event.all
        else
          @events = Event.where('event_type = ?', event_type).all
        end
      end
  end

    @events = @events.paginate(page: params[:page], per_page: 10)
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.cal_event_id = SecureRandom.hex(16)
    respond_to do |format|
      if @event.save
        # create event in Google calendar
        create_google_calendar_event(@event, CALENDAR.authorization.fetch_access_token!)

        format.html { redirect_to event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
        if @event.update(event_params)
        # update event in Google calendar
        update_google_calendar_event(@event, CALENDAR.authorization.fetch_access_token!)

        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # for deletion page
  def delete
    @event = Event.find(params[:id])
  end

  # DELETE /events/1 or /events/1.json
  def destroy

    # delete Excuse of deleted event
    Excuse.all.each do |excuse|
      if @event.id == excuse.event_id 
        excuse.destroy
      end
    end

    # delete Member_Event of deleted event
    MemberEvent.all.each do |memberevent|
      if @event.id == memberevent.event_id 
        memberevent.destroy
      end
    end

    @event.destroy
    # delete event in Google calendar
    delete_google_calendar_event(@event, CALENDAR.authorization.fetch_access_token!)

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # condition that will automatically turn point type to nil if event type is meeting
    def service_or_meeting
      if @event.event_type == 'Meeting'
        @event.point_type = nil
        @event.save
      end

      if @event.event_type == 'Service' || @event.event_type == "Personal/Non-Event"
        @event.phrase = nil
        @event.save
      end
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :point_type, :event_type, :phrase, :cal_event_id)
    end

    # Set member for authentication
    def set_member
      @user = current_admin.member
    end

    # helper methods for google calendar

    def create_google_calendar_event(event, access_token)
      calendar_id = '4e07b698012e5a6ca31301711bee1fcadccf292f6a330165b4a32afb8a850f39@group.calendar.google.com'

      # create new calendar event with necessary fields

      google_event = Google::Apis::CalendarV3::Event.new(
        id: event.cal_event_id,
        summary: event.name,
        # cool way to concatenate strings in ruby
        description: "Event type: #{event.event_type || 'N/A'}\nPoint type: #{event.point_type || 'N/A'}",
        start: {
          date: event.date.to_s
        },
        end: {
          date: event.date.to_s
        }
      )

      # insert the new Google calendar event
      CALENDAR.insert_event(calendar_id, google_event, send_notifications: true)
    end

    def delete_google_calendar_event(event, access_token)
      calendar_id = '4e07b698012e5a6ca31301711bee1fcadccf292f6a330165b4a32afb8a850f39@group.calendar.google.com'
      begin
        # delete calendar event
        CALENDAR.delete_event(calendar_id, event.cal_event_id)
      rescue Google::Apis::ClientError => e
        # do nothing if event not found
      end
    end

    def update_google_calendar_event(event, access_token)
      calendar_id = '4e07b698012e5a6ca31301711bee1fcadccf292f6a330165b4a32afb8a850f39@group.calendar.google.com'

      # find the event on the calendar by its event ID (cal_event_id)
      google_event = CALENDAR.get_event(calendar_id, event.cal_event_id)

      begin
        # update calendar event fields
        google_event.summary = event.name
        google_event.description = "Event type: #{event.event_type || 'N/A'}\nPoint type: #{event.point_type || 'N/A'}"
        google_event.start = Google::Apis::CalendarV3::EventDateTime.new(date: event.date.to_s)
        google_event.end = Google::Apis::CalendarV3::EventDateTime.new(date: event.date.to_s)

        # update calendar event
        CALENDAR.update_event(calendar_id, google_event.id, google_event, send_notifications: true)
      rescue Google::Apis::ClientError => e
        # do nothing if event not found
      end
    end

    # protects against site crashing when deleting members
    def member_admin_deletion_protection
      redirect_to new_member_path if @user.nil?
    end

    # only lets admins on certain pages
    def authenticate_admin
      redirect_to root_path if !@user.nil? && (@user.position == 'Member')
    end

    # allows admins to check off on who has access to site
    def authenticate_user
      redirect_to root_path notice: 'Pending Leadership approval' if @user.status.nil?
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <% if event.point_type? %>
    <p>
      <strong>Point type:</strong>
      <%= event.point_type %>
    </p>
  <% end%>

  <p>
    <strong>Event type:</strong>
    <%= event.event_type %>
  </p>

  <% if event.phrase? %>
    <% unless @user.position == "Member" %>
      <p>
        <strong>Phrase:</strong>
        <%= event.phrase %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :event_type, style: "display: block" %>
    <%= form.select :event_type, options_for_select([["Meeting"], ["Service"], ["Personal/Non-Event"]], selected: event.event_type)%>
  </div>

  <div>
    <%= form.label :point_type, style: "display: block" %>
    <%= form.select :point_type, options_for_select([[nil], ["Marketing"], ["Civic Engagement"], ["Social"], ["Outreach"]], selected: event.point_type) %>
  </div>

  <div>
    <%= form.label :phrase, style: "display: block" %>
    <%= form.text_field :phrase %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/delete.html.erb
<%= link_to "Back to events", events_path %>

<div class="delete">
    <h1>Destroy Event</h1>
    <%= form_for(@event, method: 'delete') do |f| %>
        <p>Are you sure you want to permanently delete this event?</p>
        <p>Name: <%= @event.name %></p>
        <p>Date: <%= @event.date %></p>
        <% if @event.point_type? %>
            <p>Point Type: <%= @event.point_type %></p> 
        <% end %>
        <p>Event Type: <%= @event.event_type %></p> 
        <% if @event.phrase?%>
            <p>Phrase: <%= @event.phrase %></p>
        <% end %>
        <div class="form-buttons">
            <%= f.submit("Delete event") %>
        </div>
    <% end %>
</div>

app/views/events/edit.html.erb
<h2>Editing event</h2>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h2>Events</h2>

<% if @user.position != "Member"%>
  <div>
    <%= link_to "New event", new_event_path %>
  </div>
<% end %>

  <iframe
    src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FChicago&showTitle=0&showPrint=0&showCalendars=0&src=NGUwN2I2OTgwMTJlNWE2Y2EzMTMwMTcxMWJlZTFmY2FkY2NmMjkyZjZhMzMwMTY1YjRhMzJhZmI4YTg1MGYzOUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%234285F4"
    style="border:solid 1px #777"
    width="800"
    height="600"
    frameborder="0"
    scrolling="no">
  </iframe>


<%# form submission for filtering events by month year etc %>
<%= form_tag events_path, method: :get do %>

  <%= select_tag "date[month]", options_for_select(Date::MONTHNAMES.compact.each_with_index.map { |month, index| [month, index+1] }), prompt: "Select month" %>
  <%= select_tag "date[year]", options_for_select((Time.now.year-1..Time.now.year+1).to_a.reverse), prompt: "Select year" %>
  <%= select_tag :event_type, options_for_select((["Any", "Meeting", "Service", "Personal/Non-Event"])), prompt: "Select event type"%> 
  <%= submit_tag "Search", class: "btn btn-primary" %>
  
<% end %>

<%= link_to "All Events", events_path%>

<%# regular code for showing the events  %>
<div id="events">
  <table class="listing" id="Member list" summary="Member list" style="width: 100%;">
    <!-- table heads -->
    <tr class="header">
      <th class="table-head">Name</th>
      <th class="table-head">Date</th>
      <th class="table-head">Point Type</th>
      <th class="table-head">Event Type</th>
      <th class="table-head">Phrase</th>
      <% @events.each do |event| %>
        <tr>
          <td> <%= event.name %></td>
          <td> <%= event.date %></td>
          <% if event.point_type? %>
            <td> <%= event.point_type %></td>
          <% else %>
            <td>n/a</td>
          <% end %>
          <td> <%= event.event_type %></td>
          <% unless @user.position == "Member" %>
            <% if event.phrase? %>
              <td> <%= event.phrase %></td>
            <% else %>
              <td> n/a </td>
            <% end %>
          <% end %>
          <!-- Actions for each member -->
          <td class="actions">
            <%= link_to("Show this event", event_path(event), class: 'action show') %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

<%# allow for you to seperate events to different pages for easier viewing%>
<%if @events.present?%>
  <%= will_paginate @events %>
<%end%>

app/views/events/new.html.erb
<h2>New event</h2>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <% unless @user.position == "Member" %>
    <%= link_to "Edit this event", edit_event_path(@event) %> |
  <% end %>
  <%= link_to "Back to events", events_path %> |

  <% unless @user.position == "Member" %>
    <%= link_to "Delete this event", delete_event_path(@event), class: "action delete" %> |
  <% end %>
</div>