config/routes.rb
Rails.application.routes.draw do
  
  resources :member_events do
    member do
      get :delete
      patch :approve
      patch :unapprove
    end
  end
  
  root "main#index"

  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end


  get 'main/index'
  resources :faqs

  # get 'members/index'
  # get 'members/new'
  # get 'members/edit'
  
  # routs for the member status pages
  get 'members/update_status', to: 'members#update_status', as: 'edit_status'
  post 'members/update_status', to: 'members#update_status', as: 'update_status'

  resources :members do
    member do
      get :delete
    end
  end

  resources :committees
  resources :excuses do 
    member do
      get :delete
    end
  end

  resources :committees do
    member do
      get :delete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :excuses do
    member do
      patch :approve
      patch :unapprove
    end
  end

  resources :events do
    member do 
      get :delete
    end
  end
  
  resources :events
end

app/models/committee.rb
class Committee < ApplicationRecord
    # set foreign key for leader member id!
    has_one :member
    belongs_to :member, optional: true

    validates :name, presence: true
    validate :formatting

    has_many :members, dependent: :nullify

    before_save do
        self.name = name.strip unless name.nil?
    end

    # ensure that correct input formats are used
    def formatting
        # name only has letters, numbers, apostraphes, and space characters
        errors.add(:name, 'name cannot have non-word characters') if !name.nil? && !name.match?(/^[\w'\s]*$/)
    end
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: %i[ show edit update destroy ]
  before_action :set_member
  before_action :member_admin_deletion_protection
  before_action :authenticate_user

  # GET /committees or /committees.json
  def index
    @committees = Committee.all
  end

  # GET /committees/1 or /committees/1.json
  def show
    @members = Member.all
  end

  # GET /committees/new
  def new
    redirect_to committees_path if !@user.nil? && (@user.position == 'Member')
    @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
    redirect_to committees_path if !@user.nil? && (@user.position == 'Member')
  end

  # POST /committees or /committees.json
  def create
    @committee = Committee.new(committee_params)

    respond_to do |format|
      if @committee.save
        format.html { redirect_to committee_url(@committee), notice: 'Committee was successfully created.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees/1 or /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to committee_url(@committee), notice: 'Committee was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    redirect_to committees_path if !@user.nil? && (@user.position == 'Member')
    @committee = Committee.find(params[:id])
    @members = Member.all
  end

  # DELETE /committees/1 or /committees/1.json
  def destroy
    @committee.destroy

    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Committee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def committee_params
      params.require(:committee).permit(:name, :member_id)
    end

    def set_member
      @user = current_admin.member
    end

    # protects against site crashing when deleting members
    def member_admin_deletion_protection
      redirect_to new_member_path if @user.nil?
    end

    # allows admins to check off on who has access to site
    def authenticate_user
      redirect_to root_path notice: 'Pending Leadership approval' if @user.status.nil?
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_committee.html.erb
<div id="<%= dom_id committee %>">
  <p>
    <strong>Name:</strong>
    <%= committee.name %>
  </p>

  <p>
    <strong>Director:</strong>
    <% if committee.member.present? %>
      <%= committee.member.name %>
    <% else %>
      None
    <% end %>
  </p>

</div>

app/views/committees/_form.html.erb
<%= form_with(model: committee) do |form| %>
  <% if committee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
        <% committee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :member_id, style: "display: block" %>
    <%= form.select :member_id, Member.order(:name).map { |member| [ member.name, member.id] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/committees/delete.html.erb
<%= link_to "Back to committees", committees_path %>

<div class="delete">
    <h1>Destroy Committe</h1>

    <%= form_for(@committee, method: 'delete') do |f| %>
        <p>Are you sure you want to permanently delete this committee?</p>
        <p>Name: <%= @committee.name %></p>
        <p>Director: <%= @committee.member.name %></p>
        <p>Members:</p>
        <% @members.each do |member| %>
          <% if member.committee_id == @committee.id %>
            <li><%= member.name %></li>
          <% end %>
        <% end %>
        <br>
        <div class="form-buttons">
            <%= f.submit("Delete committee") %>
        </div>
    <% end %>
</div>

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render "form", committee: @committee %>

<br>

<div>
  <%= link_to "Show this committee", @committee %> |
  <%= link_to "Back to committees", committees_path %>
</div>

app/views/committees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Committees</h1>

<div id="committees">
  <% @committees.each do |committee| %>
    <%= render committee %>
    <p>
      <%= link_to "Show this committee", committee %>
      <%if @user.position != "Member"%> |
        <%= link_to "Edit this committee", edit_committee_path(committee) %> |
        <%= link_to "Delete this committee", delete_committee_path(committee), class: "action delete" %>
      <% end %>
    </p>
  <% end %>
</div>
<%if @user.position != "Member"%>
  <%= link_to "New committee", new_committee_path %>
<% end %>

app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render "form", committee: @committee %>

<br>

<div>
  <%= link_to "Back to committees", committees_path %>
</div>

app/views/committees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @committee %>

<div>
  <strong>Members:</strong>

  <% @members.each do |member| %>
    <% if member.committee_id == @committee.id %>
      <li><%= member.name %></li>
    <% end %>
  <% end %>
</div>

<br>

<div>
  <%if @user.position != "Member"%>
    <%= link_to "Edit this committee", edit_committee_path(@committee) %> |
    <%= link_to "Delete this committee", delete_committee_path(@committee), class: "action delete" %> |
  <% end %>
  <%= link_to "Back to committees", committees_path %>
</div>