config/routes.rb
Rails.application.routes.draw do
  
  resources :member_events do
    member do
      get :delete
      patch :approve
      patch :unapprove
    end
  end
  
  root "main#index"

  # root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end


  get 'main/index'
  resources :faqs

  # get 'members/index'
  # get 'members/new'
  # get 'members/edit'
  
  # routs for the member status pages
  get 'members/update_status', to: 'members#update_status', as: 'edit_status'
  post 'members/update_status', to: 'members#update_status', as: 'update_status'

  resources :members do
    member do
      get :delete
    end
  end

  resources :committees
  resources :excuses do 
    member do
      get :delete
    end
  end

  resources :committees do
    member do
      get :delete
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :excuses do
    member do
      patch :approve
      patch :unapprove
    end
  end

  resources :events do
    member do 
      get :delete
    end
  end
  
  resources :events
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoveTxProj Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <!-- Navigation bar  -->
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
      <!-- Collapse Section -->
      <div class="collapse navbar-collapse" id="navbarColor01">
        <!-- Navbar menu -->
        <ul class="navbar-nav mr-auto">
          <!-- Navbar Items -->
          <li class="nav-item">
            <%= image_tag "move tx logo.JPG", class: 'nav-logo'  %>
          </li>
          <li class="nav-item <%= active_class(root_path) %>">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <%# admin specific display  %>
          <% if !@user.nil? %>
            <% if @user.position != 'Member' %>
              <li class="nav-item <%= active_class(member_events_path) %>">
                <%= link_to "New Member Approval", update_status_path, class: 'nav-link' %>
              </li>
              <li class="nav-item <%= active_class(members_path) %>">
                <%= link_to "Member List", members_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item <%= active_class(committees_path) %>">
              <%= link_to "Committees", committees_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= active_class(excuses_path) %>">
              <%= link_to "Excuses", excuses_path, class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item <%= active_class(events_path) %>">
            <%= link_to "Events", events_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= active_class(member_events_path) %>">
            <%= link_to "Activities", member_events_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    <!-- Checks if the user is logged in as to not display invalid information -->
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "FAQ", faqs_path(format: :html), class: 'nav-link-sep' %>
          </li>
          <% if !@user.nil? %>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link-sep' %>
            </li>
            <li class="nav-item">
              <img src="<%= current_admin.avatar_url %>" class='nav-avatar' referrerpolicy="no-referrer"/>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>